# Generated by Django 3.2.7 on 2021-09-30 11:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='image/upload/v1531667999/default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
